# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-29 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.IntegerField(default=0)),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('url', models.URLField(default='', max_length=300)),
                ('body', models.TextField(default='', max_length=800)),
                ('address', models.CharField(default='', max_length=200)),
                ('source', models.URLField(default='', max_length=300)),
                ('stars', models.CharField(default='', max_length=300)),
                ('tipo', models.CharField(default='', max_length=300)),
                ('puntuacion', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HotelsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteles.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.IntegerField(default=0)),
                ('url', models.URLField(default='', max_length=300)),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteles.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='PagUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=300)),
                ('title', models.CharField(default='', max_length=300)),
                ('color', models.CharField(default='', max_length=300)),
                ('size', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='com',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteles.Hotel'),
        ),
    ]
